version: 0.2

phases:
  pre_build:
    commands:
      - echo Retrieving Docker Hub credentials from Secrets Manager...
      - export DOCKER_USERNAME=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:ap-south-1:339712721384:secret:dockerhublogin-4vcmMW --query SecretString --output text | jq -r .username)
      - export DOCKER_PASSWORD=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:ap-south-1:339712721384:secret:dockerhublogin-4vcmMW --query SecretString --output text | jq -r .password)
      - echo Logging in to Docker Hub...
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Building the Docker image..."
      - docker build -t webapp .
      - mkdir -p game/dist # Ensure the directory exists
      - echo "Build completed on $(date)"

  post_build:
    commands:
      - echo "Listing contents of the build directory..."
      - ls -la game/
      - echo "Listing contents of game directory..."
      - ls -la game/dist/
      - echo "Uploading game executable to S3..."
      - aws s3 cp game/dist/game s3://builddb/game
      - echo "Tagging the Docker image..."
      - docker tag webapp:latest "$DOCKER_USERNAME/webapp:latest"
      - echo "Pushing the Docker image..."
      - docker push "$DOCKER_USERNAME/webapp:latest"
      - echo "Build completed on $(date)"
